### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by gewondjan** [byuitechops/upload-course#6]
```
upload-course\… fatalError                message: Unknown error occurred. Please check the status of the migration via Canvas UI stack: Error: Unknown error occurred. Please check the status of the migration via Canvas UI
    at canvas.get (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\upload-course\uploadCourse.js:35:38)
    at paginate (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:32:9)
    at Object.callReturned [as callback] (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:228:9)
    at C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:2271:31
    at C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:969:16
    at updateRateLimit (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:122:17)
    at updateRateLimit (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:58:9)
    at Request.request [as _callback] (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:108:13)
    at Request.self.callback (C:\Users\jedimasterryan\repos\d2l-to-canvas-conversion-tool\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
```

**Comment by gewondjan** [comment]
This is a Canvas Issue
